### ISSUE TITLE
Assertion mixing virtual and real postings with same account is broken

### ISSUE THREAD

**Issue by valcomm** [ledger/ledger#1959]
Ledger
```
commodity $
  note American Dollars
  format $1,000.00
  alias USD
  ; default

account Assets:Current Assets:Checking Account
account Assets:Debts:Reimb
account Expenses:Miscellaneous
account Liabilities:Credit Card

2020-04-04 Amazon.com
  Expenses:Miscellaneous  USD 10
  Liabilities:Credit Card  USD -10
  (Assets:Debts:Reimb)  USD 10

2020-04-11 Amazon.com
  Expenses:Miscellaneous  USD 20
  Liabilities:Credit Card  USD -20
  (Assets:Debts:Reimb)  USD 20

2020-04-15 reimb
  Assets:Current Assets:Checking Account  USD 30
  Assets:Debts:Reimb  USD -30 = 0

```

compiled ledger from commit 718ba0e3139d365ffb7883cb2c937cfe23656506

```
$ ./ledger --version
Ledger 3.2.1-20200518, the command-line accounting tool

Copyright (c) 2003-2019, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.
$ ./ledger -f /tmp/ledger/temp.ledger bal
While parsing file "/tmp/ledger/temp.ledger", line 24:
While parsing posting:
  Assets:Debts:Reimb  USD -30 = 0
                                ^
Error: Balance assertion off by $30.00 (expected to see $-30.00)
```

at the same time on the same ledger file system ledger:
```
$ ledger --version
Ledger 3.1.2-20190205, the command-line accounting tool

Copyright (c) 2003-2019, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.
 $ ledger -f /tmp/ledger/temp.ledger bal
              $30.00  Assets:Current Assets:Checking Account
              $30.00  Expenses:Miscellaneous
             $-30.00  Liabilities:Credit Card
--------------------
              $30.00
```

**Comment by daraul** [comment]
I believe I made a mistake in my previous statement, I don't believe what I was thinking of doing would work. The assertion made to the `Assets:Debts:Reimb` account is wrong because it's made to a *real* account, whereas all previous postings were made to it's virtual counterpart (`(Assets:Debts:Reimb)`). 

Therefore the correct assertion would be `(Assets:Debts:Reimb)  USD -30 = 0`

And your final transaction would become

```
2020-04-15 reimb
  Assets:Current Assets:Checking Account  USD 30
  Assets:Debts:Reimb  USD -30
  (Assets:Debts:Reimb)  USD -30 = 0
```
---

That said, I am wondering if it might be useful to provide some new syntax for the user to be explicit in whether or not they're attempting to assert an account's virtual, or real balance. 

Maybe something like this to assert the virtual balance:

```
Assets:Debts:Reimb  USD -30 = 0
``` 

and this to assert the real balance:

```
Assets:Debts:Reimb  USD -30 == USD -30
```
---

Personally, I prefer leaving things as they are. You added an extra posting to put the money into the virtual account, why not use another posting to take it back out? That's just me, though.

**Comment by valcomm** [comment]
I think there's a confustion between an account and a posting.  Account is singular entity (no real/virtual sides of it).  And transaction exists of regular postings (the ones that balance) and optional virtual postings (that might not balance).
At the end `bal` says that there is no any amount on Assets:Debts:Reimb account (aka = 0) for the provided example.
For me it looks like assertion takes amounts before virtual postings applied.  While version 3.1.2 was using amounts after virtual postings applied and it was working according the current documentation and syntax

**Comment by daraul** [comment]
Yes, there are virtual/real sides to an account. At least __now__ there are. In 3.1.2 an account's "real", or "virtual" balance was one and the same, meaning that the user could only assert an account's virtual balance, and not the real one. This was considered a bug as noted in #543, and it was fixed to allow the user to perform assertions on the account's real balance, by simply putting "... = 0 USD" on the real account's posting, and "... 100 USD" on the virtual account's posting. 

You __can__ assert your virtual account's amount, but you'd have to update your transaction like I've outlined above. 

If you have any ideas on an alternative syntax that could get around this I'd be happy to see it..

**Comment by valcomm** [comment]
I think the issue in [#543](https://github.com/ledger/ledger/issues/543) wasn't fixed correctly.  As I mentioned before, account is a single entity.  Documentation only mentions "virtual postings", not "virtual accounts".  I'd say fix for 543 should be reverted.  Otherwise it'll grow in some monstrosity with not clear definition of what exactly is "virtual part of account" and what operations on it supported/allowed (e. g. how do I see the current balance of the virtual part of some account?  `ledger bal`?).
It's better to have a limited and well defined scope of "virtual postings".
And you are right about the need of new syntax to assert the real balance (the one that is shown by `ledger --real bal`).  I think `==` is a very good suggestion.  If it's presented it defines an assertion for `--real` option.  If it's not - existing `= 0` applies to both (like in my case above)
And if #543 reverted and new syntax is introduced (which in total makes a very small addition to the documentation and doesn't introduce any extra entity) example from #543 would become:
```
2018/01/01 * Opening Balance
    Assets:Checking                                    $100.00
    Equity:Opening Balances

2018/01/01 * Budget
    [Assets:Checking]                                 -$100.00
    [Assets:Budget:Food:Groceries]                      $20.00
    [Assets:Budget:Food:Restaurants]                    $80.00

2018/01/02 * Assertion
    Assets:Checking                                  = $0.00  == $100.00
```
and while processing file, ledger doesn't need to keep track of both real/virtual postings.  It only tracks the one defined by command line option: without `--real` keep tracks of all postings and only considers assertions with single `=`.  But if `--real` was provided, virtual postings are ignored and for assertions `==` is used if presented, otherwise `=`.

What do you think about such suggestion?  Did I miss something?

**Comment by daraul** [comment]
I think you did miss something. The documentation mentions "virtual accounts" and "real accounts" multiple times. 

---

From my understanding a "virtual posting" is simply a posting you would have omitted when passing the `--real` option. 

As to the new syntax I can't speak whether or not it'd be the better option from a performance or "lines of code" perspective. I am not sure who I could mention that might know. 

Personally, however, I don't like the syntax change. Explicitly stating the account (virtual or real) that you're asserting the balance of makes the most sense to me. It would also make the most sense to non-developers like my accountant. 

---

At the very least, I think a documentation change is necessary: You mentioned it being inconsistent with how ledger works right now; can you point to an example? I can't find any.

**Comment by valcomm** [comment]
Yes, I saw "virtual accounts" in the documentation.  All 7 mentions.  Some of those are for a different thing (transaction codes), some are misused (5.8 uses "virtual account", but actually means "virtual posting" I think).

I totally agree with your definition of "virtual posting".  But what is "virtual account" then?  Or maybe even "virtual side of an account"?
"Virtual posting" by such definition is scoped and well defined.  They affect the account balance (or not with `--real`), their results are displayed by `bal`.  This is all good.  The missing thing is assertion mixing virtual and real postings.  If `bal` shows me the result, I think it's only reasonable to be able to have assertion to the same result.  And if `--real bal` is used and it shows the different result, there should be a way to have an assertion to that result.

Now to the "virtual accounts" or "virtual sides of the account".  I have no definition for those.  What are they?  What's their effect?  What operations are allowed?

As soon as it's decided, if there will be "virtual postings" or "virtual accounts", documentation changes could be decided.
If it's only "virtual postings",  5.8 should be `s/virtual account/virtual posting/g`.  For 6.4.1 in the same way, though not automatic. 3.8 most likely could stay as it uses "virtual accounts" to explain "transaction codes".  Not so sure what would be the better substitution.  Probably could just stay.
I think there's need for "5.10.1.2 Balance assertions for accounts with virtual postings".  Either an explanation how assertion should be different from what's shown by `bal`.  Or explanation that assertions in such cases are only when there is no `--real`.  Or new syntax for `--real`.

**Comment by daraul** [comment]
You can see the virtual balance of an account by using `bal`, and assert the balance of that account like so:  `[Assets:Checking]  -10 USD = 0 USD`. That will assert that the balance of the virtual account is 0. 

If you wish to assert the real balance of the account you do the same thing, but without the brackets: `Assets:Checking  -10 USD = 10 USD`. This will assert the real balance of the account is 10 USD. 

A virtual account can be described as an account whose balance includes virtual postings, I suppose.

**Comment by simonmichael** [comment]
I fully agree with valcomm's mental model, and I have to think it was a bad idea to try and make accounts virtual/real. Balanced/unbalanced postings, to the same accounts, is much simpler and less confusing. This change also increases incompatibility with hledger, ie it's harder to export a hledger journal to Ledger.

**Comment by jwiegley** [comment]
I don't like this idea of varying the interpretation based on whether "any real postings were found". So, closing this as expected behavior.

**Comment by simonmichael** [comment]
Hi John - I re-read this issue and found it a bit confusing, so did some testing. Here's a repro of OP's issue:

```
2020-04-04
    (Assets:Debts:Reimb)                      USD 10

2020-04-11
    (Assets:Debts:Reimb)                      USD 20

2020-04-15
    (Assets:Debts:Reimb)                       USD 0 = USD 30   ; ledger accepts this
    Assets:Debts:Reimb                         USD 0 = USD 30   ; ledger rejects this
```

Is that how you understood it ?

To clarify my 2023 comment: in hledger, accounts and account balances are not real or virtual, only postings are. Tracking a separate real balance and virtual balance in each account seems like a not-useful complication ?

**Comment by jwiegley** [comment]
Hi Simon,

Thanks for writing. Can you say a little bit more about the semantics of how you support only virtual postings? I think Ledger is just tracking two separate balances right now to make sure they balance in the end. A virtual posting cannot cause an account to satisfy its balance assertion. The virtual posting is really only there to contribute to a different display in the end.

I originally invented virtual postings so that ancillary accounting schemes could be tracked. For example, one accounting scheme would be accounts representing physical locations where assets are held, but another could be funds for which money is reserved. In that scenario, I wanted to be able to contribute money to a checking account, but the same amount might then be allocated to two funds. These two separate realities should independently balance, but only one of them is real. This is why I chose a virtual account rather than just a virtual posting, but I'm a bit more interested in how postings work in H Ledger when they're virtual.

**Comment by simonmichael** [comment]
Certainly.. from https://hledger.org/hledger.html#virtual-postings , the hledger semantics are like this:

> A posting with parentheses around the account name, like `(some:account) 10`, is called an unbalanced virtual posting. These postings do not participate in transaction balancing. 
> (And if you write them without an amount, a zero amount is always inferred.)

In hledger, that's the only thing special about them - they're ignored when checking that a transaction is balanced. But they have a real effect on account balances, just like any other posting. And similarly,

> A posting with brackets around the account name ([some:account]) is called a balanced virtual posting. The balanced virtual postings in a transaction must add up to zero, just like ordinary postings, but separately from them.

"Balanced virtual postings" need to balance only each other within the transaction. But they too affect account balances like any other posting.

This isn't the only way things could work, but I find it easy to reason about and free of complications like how should balance assertions and balance assignments behave when you enable/disable virtual postings, what if you mix real/virtual/balanced-virtual postings in an account, etc.

**Comment by jw-pos** [comment]
I see, that does sound quite a bit simpler. I'm a bit averse at this moment to change any core behaviors that might affect expectations or the way that user's data is currently being processed, but I will certainly keep this in mind.
